# Copyright (c)  WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Old: 3
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ing1
  namespace: default
  creationTimestamp: "2020-10-03T00:00:01Z"
  annotations:
    kubernetes.io/ingress.class: "microgateway"
spec:
  backend:
    serviceName: products-default
    servicePort: 80
  tls:
    - secretName: foo-prod
      hosts:
        - prod.foo.com
    - secretName: foo-dev
      hosts:
        - dev.foo.com
  rules:
    - host: "*.foo.com"
      http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact
              servicePort: 8080
    - host: prod.foo.com
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              serviceName: products-prefix
              servicePort: 8080
    - host: deprecated.foo.com
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              serviceName: products-prefix
              servicePort: 8080

---
# Old: 1
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ing2
  namespace: default
  creationTimestamp: "2020-10-01T00:00:01Z"
  annotations:
    kubernetes.io/ingress.class: "microgateway"
spec:
  tls:
    - secretName: bar-prod
      hosts:
        - prod.bar.org
  rules:
    - host: "*.bar.com"
      http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact
              servicePort: 8080
    - http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact
              servicePort: 8080

---
# Old: 2
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ing3
  namespace: default
  creationTimestamp: "2020-10-02T00:00:01Z"
  annotations:
    kubernetes.io/ingress.class: "microgateway"
spec:
  tls:
    - secretName: bar-prod2
      hosts:
        - prod.bar.org
  rules:
    - host: "*.bar.com"
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              serviceName: products-prefix
              servicePort: 8080
      # Override ing2 /products
    - host: "*.bar.com"
      http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact-override
              servicePort: 8080
    - host: "deprecated.bar.com"
      http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact-override
              servicePort: 8080

---
# Old: 4
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ing4
  namespace: default
  creationTimestamp: "2020-10-04T00:00:01Z"
  annotations:
    kubernetes.io/ingress.class: "microgateway"
spec:
  tls:
    - secretName: bar-prod
      hosts:
        - prod.bar.org
  rules:
      # Override ing1 /products prefix
    - host: prod.foo.com
      http:
        paths:
          - path: /products
            pathType: Prefix
            backend:
              serviceName: products-prefix
              servicePort: 8080
    # Override ing2 /products
    - http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-override
              servicePort: 8080