apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: default
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
---

apiVersion: v1
kind: Service
metadata:
  name: products-exact
  namespace: default
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
---

apiVersion: v1
kind: Service
metadata:
  name: products-prefix
  namespace: default
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
---

apiVersion: v1
kind: Service
metadata:
  name: products-exact-override
  namespace: default
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
