apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: products-privatejet
  labels:
    app: wso2
spec:
  protocol: http
  port: 80
  targetPort: 9090
  deploy:
    name: products-pj-service
    dockerImage: pubudu/products:1.0.0
    count: 2
  mode : privateJet