apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securities.wso2.com
spec:
  group: wso2.com
  names:
    kind: Security
    listKind: SecurityList
    plural: securities
    singular: security
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: SECURITY_TYPE
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Security is the Schema for the securities API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecuritySpec defines the desired state of Security
            properties:
              securityConfig:
                items:
                  properties:
                    alias:
                      type: string
                    audience:
                      type: string
                    certificate:
                      type: string
                    credentials:
                      type: string
                    endpoint:
                      type: string
                    issuer:
                      type: string
                    validateAllowedAPIs:
                      type: boolean
                    validateSubscription:
                      type: boolean
                  required:
                  - alias
                  - audience
                  - certificate
                  - credentials
                  - endpoint
                  - issuer
                  type: object
                type: array
              type:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book.kubebuilder.io/beyond_basics/generating_crd.html'
                type: string
            required:
            - securityConfig
            - type
            type: object
          status:
            description: SecurityStatus defines the observed state of Security
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
