
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "products"
    version: "1.0.0"
  name: "products"
spec:
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9090
      name: "http"
  selector:
    app: "products"
    version: "1.0.0"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    version: "1.0.0"
    app: "products"
  name: "products-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1.0.0"
      app: "products"
  template:
    metadata:
      annotations: {}
      labels:
        version: "1.0.0"
        app: "products"
    spec:
      containers:
        - image: "pubudu/products:1.0.0"
          imagePullPolicy: "Always"
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            tcpSocket:
              port: 9090
          name: "products-deployment"
          ports:
            - containerPort: 9090
              protocol: "TCP"
      nodeSelector: {}