# Update ing 1
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ing1
  namespace: default
  creationTimestamp: "2020-10-03T00:00:01Z"
  annotations:
    kubernetes.io/ingress.class: "microgateway"
spec:
  backend:
    serviceName: products
    servicePort: 80
  tls:
    - secretName: foo-prod
      hosts:
        - prod.foo.com
    - secretName: foo-dev
      hosts:
        - dev.foo.com
  rules:
    - host: "*.foo.com"
      http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact
              servicePort: 8080