apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: petstore-swagger-io
  namespace: wso2-system
  labels:
    app: wso2
spec:
  protocol: https
  port: 443
  deploy:
    name: myservice
    dockerImage: nginx:latest
    count: 3
  mode : privateJet
