kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: analytics-pv-claim
  namespace: wso2-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi