# Update ing 1
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ing1
  namespace: default
  # Make ResourceVersion as 1 since this is first update
  resourceVersion: "1"
  annotations:
    kubernetes.io/ingress.class: "microgateway"
spec:
  backend:
    serviceName: products
    servicePort: 80
  tls:
    - secretName: foo-dev
      hosts:
        - dev.foo.com
    - secretName: no-existing-secret
      hosts:
        - no.existing-secret-host.com
  rules:
    - host: "*.foo.com"
      http:
        paths:
          - path: /products
            pathType: Exact
            backend:
              serviceName: products-exact
              servicePort: 8080
    - host: "*.no-service.com"
      http:
        paths:
          - path: /no-service-updated-in-ing1
            pathType: Exact
            backend:
              serviceName: products
              servicePort: 8080