apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: wso2-system
type: Opaque
data:
  username: YWRtaW4=               #enter base64 encoded username for analytics
  password: YWRtaW4=               #enter base64 encoded password for analytics
  cert_security: Y2VydC1zZWNyZXQ=  #enter (base64 encoded) name of the secret with certificate