apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: helloworld-private
  labels:
    app: wso2
spec:
  protocol: http
  port: 80
  deploy:
    name: helloworldservice
    dockerImage: shehani123/helloworld:v1
    count: 2
  mode : privateJet