apiVersion: wso2.com/v1alpha1
kind: TargetEndpoint
metadata:
  name: review-ep
  labels:
    app: wso2
spec:
  protocol: http
  port: 80
  targetPort: 8080
  deploy:
    name: reviewservice
    dockerImage: pubudu/review:1.0.0
    count: 1
