apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apis.wso2.com
spec:
  group: wso2.com
  names:
    kind: API
    listKind: APIList
    plural: apis
    singular: api
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: API is the Schema for the apis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: APISpec defines the desired state of API
          properties:
            definition:
              description: Definition contains api definition related values
              properties:
                configmapName:
                  type: string
                type:
                  type: string
              required:
              - configmapName
              - type
              type: object
            interceptors:
              properties:
                ballerina:
                  type: string
                java:
                  items:
                    type: string
                  type: array
              required:
              - ballerina
              - java
              type: object
            mode:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            override:
              type: boolean
            replicas:
              type: integer
            updateTimeStamp:
              type: string
          required:
          - definition
          - interceptors
          - mode
          - override
          - replicas
          - updateTimeStamp
          type: object
        status:
          description: APIStatus defines the observed state of API
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
